// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EfRepository.DbEntity;

public partial class CustomerBankInfo
{
    public int BankInfoId { get; set; }

    public int CustomerId { get; set; }

    public string BankName { get; set; }

    public string AccountNumber { get; set; }

    public string Currency { get; set; }

    public decimal Balance { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual CustomerInfo Customer { get; set; }

    public virtual ICollection<CustomerTransInfo> CustomerTransInfos { get; set; } = new List<CustomerTransInfo>();
}