// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EfRepository.DbEntity;

public partial class CustomerInfo
{
    public int CustomerId { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<CustomerBankInfo> CustomerBankInfos { get; set; } = new List<CustomerBankInfo>();

    public virtual ICollection<CustomerTransInfo> CustomerTransInfos { get; set; } = new List<CustomerTransInfo>();
}