// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EfRepository.DbEntity;

public partial class SysAdmin
{
    public int AdminId { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string DisplayName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsActive { get; set; }
}